
services:
  backup-tool:
    build: .
    container_name: nestjs-backup-tool
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    ports:
      - "5004:3000"
    volumes:
      - ./storage:/usr/src/app/storage
    environment:
      - NODE_ENV=development