
services:
  backup-tool:
    build: .
    image: ghcr.io/kl-admin-git/backup-tool:latest
    container_name: nestjs-backup-tool
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    ports:
      - "5004:3000"
    env_file:
      - ${ENV_FILE:-.env.db.docker}
    volumes:
      - ./storage:/usr/src/app/storage
      - ./${ENV_FILE:-.env.db.docker}:/usr/src/app/.env
      - ./${CONEXION_FILE:-conexion_backup.json}:/usr/src/app/conexion_backup.json
    environment:
      - NODE_ENV=production